### ISSUE TITLE
TypeError: LlamaDecoderLayer.__init__() missing 1 required positional argument: 'layer_idx'

### ISSUE THREAD

**Issue by frankdarkluo** [4AI/LS-LLaMA#11]
When I am using the modeling_llama.py in your code. I run into the issue:

```
File "/home/xxx/DPO-eval/modeling_llama.py", line 59, in <listcomp>
self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
TypeError: LlamaDecoderLayer.__init__() missing 1 required positional argument: 'layer_idx'
```
My transformer version is updated to 4.37.1. 

In addition, I wonder if huggingface has a wrapped version of your "UnmaskingLlamaForSequenceClassification" and "UnmaskingLlamaForTokenClassification"?

**Comment by SeanLee97** [comment]
hi @frankdarkluo, It seems that the implementation of LLaMA in Transformers has been updated. Could you degrade the transformers version to "transformers==4.32.1"? 
We are finding solutions to be compatible with the new version.

**Comment by qiuhaolu** [comment]
I met this same error.

**Comment by SeanLee97** [comment]
> I met this same error.

@qiuhaolu have you tried to downgrade the transformers to 4.32.1?

**Comment by qiuhaolu** [comment]
> > I met this same error.
> 
> @qiuhaolu have you tried to downgrade the transformers to 4.32.1?

Yes it works now. Thank you.
