### ISSUE TITLE
downgraded to transformers 4.32.1 still got error

### ISSUE THREAD

**Issue by qiuhaolu** [4AI/LS-LLaMA#12]
RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
cannot import name 'is_fairscale_available' from 'transformers.integrations'

**Comment by qiuhaolu** [comment]
solved

**Comment by DavidLi1111** [comment]
I recently encountered the same issue. Could you share your solution to fix this problem?

**Comment by qiuhaolu** [comment]
> I recently encountered the same issue. Could you share your solution to fix this problem?

I clean installed the specific version of transformers.

**Comment by DavidLi1111** [comment]
Thank you for sharing your solution. I found that updating the transformers to version 4.35 or higher resolved the problem.
