### ISSUE TITLE
Ask pretrained weights

### ISSUE THREAD

**Issue by anhnh2002** [4AI/LS-LLaMA#16]
How can i get pretrained weights?

**Comment by SeanLee97** [comment]
hi, we didn't opensource our model. You can reproduce our results using our code.

B.T.W, recently we started a new project [BiLLM](https://github.com/WhereIsAI/BiLLM) to train BiLLM models easily. 
Based on this, we open source [llama-7b-conll03](https://huggingface.co/WhereIsAI/billm-llama-7b-conll03-ner) model. 
More models are coming! Welcome to follow us on HuggingFace: https://huggingface.co/WhereIsAI
