### ISSUE TITLE
LoRA seems not training the linear head for classification

### ISSUE THREAD

**Issue by mutetea** [4AI/LS-LLaMA#3]
For llama_seq_clf，it seems you just use LlamaForSeq Classification，which use a new linear head to substitute the original head. 

I don't think LoRA train this layer，why this is not an issue？

**Comment by SeanLee97** [comment]
Hi @mutetea, sorry for the delayed relay. 

For `LlamaForSequenceClassification`, we use the official implementation. The classification layer with the name `classifier` is automatically added to the trainable parameters in PEFT, you can check this: https://github.com/huggingface/peft/blob/main/src/peft/peft_model.py#L788-L791

Actually, I am not very clear on your question. If you still have questions, please let me know.
